print("DESAFIO 05")
n1=int (input("Digite um número: "))
print(f"O antecessor do seu valor é {n1-1} \nO sucessor é {n1+1}")
print("DESAFIO 06")
print(f"O dobro do seu número é {2*n1} \nO triplo é {3*n1} \nE a raiz é {n1**(1/2)}")
print("DESAFIO 07")
nota1=float (input("Qual foi a sua primeira nota? "))
nota2=float (input("Qual foi a sua segunda nota? "))
media=(nota1+nota2)/2
print(f"sua média é {media}")
print("DESAFIO 08")
m=float (input("Qual sua altura em metros? "))
cm=m*100
mm=cm*100
print(f"Sua altura em cm é {cm}cm e sua altura em milimetros é {mm}mm")
print("DESAFIO 09")
n2=int (input("Digite um número "))
print (f"1x{n2}={n2*1} \n2x{n2}={n2*2} \n3x{n2}={n2*3} \n4x{n2}={n2*4} \n5x{n2}={n2*5} ")
print("DESAFIO 10")
reais=float (input("Quantos Reais você tem no momento? "))
print(f"Com R${reais} Você pode comprar ${reais/5.06}")
print("DESAFIO 11")
largura=float (input("Qual a largura da sua parede em metros? "))
altura=float (input("Qual a altura da sua parede em metros? " ))
mq=largura*altura
print (f"A sua parede tem {mq}metros quadrados")
print(f"para pintar sua parede é necessario {mq/2}L de tinta")
print("DESAFIO 12")
preco=float (input("Qual o valor antigo do seu celular?"))
print(f"O valor com desconto de 5% é de R${preco-(preco/100)*5}")
print("DESAFIO 13")
sal=float (input("Qual seu salário atual?"))
print(f"Seu novo salario é de {sal+(sal/100)*15}")